### ISSUE TITLE
Cannot use Laravel broadcasting with multitenancy for realtime communication in Landlord when queues_are_tenant_aware and vice versa

### ISSUE THREAD

**Issue by 3assy2018** [spatie/laravel-multitenancy#139]
Env:

PHP 7.4.8
Laravel 7.0
OS: Windows
Local Server Client: Laragon

```php
<?php

class TestEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $content = "Hello";

    public function broadcastOn()
    {
        return new Channel('test');
    }
}
```

And listener:

```php
<?php

class OnTestEvent implements ShouldQueue, NotTenantAware
{
    use InteractsWithQueue;

    public function handle(TestEvent $event)
    {
        //
    }
}
```

Also tried jobs:

```php
<?php

class TestJob implements ShouldQueue, ShouldBroadcast, NotTenantAware
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, InteractsWithSockets;

    public $content = 'Hello From Job';

    public function handle()
    {
        //
    }

    public function broadcastOn()
    {
        return new Channel('test');
    }
}
```

when queues_are_tenant_aware and I try to dispatch non-tenant aware ShouldBroadcast job I receive in my log:

```
[2020-09-20 19:25:25] local.ERROR: The current tenant could not be determined in a job named `Illuminate\Queue\CallQueuedHandler@call`. No `tenantId` was set in the payload. {"exception":"[object] (Spatie\\Multitenancy\\Exceptions\\CurrentTenantCouldNotBeDeterminedInTenantAwareJob(code: 0): The current tenant could not be determined in a job named `Illuminate\\Queue\\CallQueuedHandler@call`. No `tenantId` was set in the payload. at C:\\laragon\\www\\test-mt\\vendor\\spatie\\laravel-multitenancy\\src\\Exceptions\\CurrentTenantCouldNotBeDeterminedInTenantAwareJob.php:12)
[stacktrace]
#0 C:\\laragon\\www\\test-mt\\vendor\\spatie\\laravel-multitenancy\\src\\Actions\\MakeQueueTenantAwareAction.php(74): Spatie\\Multitenancy\\Exceptions\\CurrentTenantCouldNotBeDeterminedInTenantAwareJob::noIdSet(Object(Illuminate\\Queue\\Events\\JobProcessing))
#1 C:\\laragon\\www\\test-mt\\vendor\\spatie\\laravel-multitenancy\\src\\Actions\\MakeQueueTenantAwareAction.php(48): Spatie\\Multitenancy\\Actions\\MakeQueueTenantAwareAction->findTenant(Object(Illuminate\\Queue\\Events\\JobProcessing))
#2 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(381): Spatie\\Multitenancy\\Actions\\MakeQueueTenantAwareAction->Spatie\\Multitenancy\\Actions\\{closure}(Object(Illuminate\\Queue\\Events\\JobProcessing))
#3 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Queu...', Array)
#4 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(511): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Queu...')
#5 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(343): Illuminate\\Queue\\Worker->raiseBeforeJobEvent('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob))
#6 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(306): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#7 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#8 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'tenants_db,defa...', Object(Illuminate\\Queue\\WorkerOptions))
#9 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'tenants_db,defa...')
#10 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#11 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): call_user_func_array(Array, Array)
#12 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#17 C:\\laragon\\www\\test-mt\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 C:\\laragon\\www\\test-mt\\vendor\\symfony\\console\\Application.php(916): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 C:\\laragon\\www\\test-mt\\vendor\\symfony\\console\\Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 C:\\laragon\\www\\test-mt\\vendor\\symfony\\console\\Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 C:\\laragon\\www\\test-mt\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 C:\\laragon\\www\\test-mt\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"} 
```

If anyone could help with solution it would be great, thanks.

**Comment by masterix21** [comment]
Hi @3assy2018, I tried following your code but works. Could you create a repository with your full code to understand better?

Thanks

**Comment by 3assy2018** [comment]
Yes, this code works but only if you set a tenant, but if you try to fire the event without tenant awareness, it gives an error that no tenant was set, this happens when queues_are_tenant_aware is set to true, if I set it to false the code fires correctly but if I used the interface TenantAware, it cannot detect tenant and gives an error of need a tenant.

**Comment by masterix21** [comment]
I'm digging inside your problem: please follow the PR #140: I will merge it asap.

**Comment by 3assy2018** [comment]
Thanks very much

**Comment by masterix21** [comment]
@3assy2018 released the version 1.6.8.

Please note that you need to change your code as below:

```php
class TestEvent implements ShouldBroadcast, NotTenantAware
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $content = "Hello";

    public function broadcastOn()
    {
        return new Channel('test');
    }
}
```

So, from the listener you can remove the `NotTenantAware` interface.

Please give me feedback. Thanks

**Comment by 3assy2018** [comment]
Dear Masterix21,

Thanks for your effort, seriously I tried the provided code and I found that the same error happens.
I took a small trip inside MakeQueueTenantAwareAction and I started to debug its behavior and what are entities used and finally I found that there was a use line at the top of the file was missing so I made a quick edit with pull request number #142 to add this line, and it was tested and working.

Thanks for you patience.

**Comment by masterix21** [comment]
@3assy2018, thanks for your PR.

Sorry but I don't understand if now, with your PR, the issue is solved. Please keep us updated.

Thank you again.

**Comment by 3assy2018** [comment]
Yes it is working like a charm now and detects Awareness interfaces correctly, thanks for your effort

**Comment by masterix21** [comment]
I'm happy to hear it. Great!
