### ISSUE TITLE
migration undefined contant STDIN

### ISSUE THREAD

**Issue by rogerad** [spatie/laravel-multitenancy#248]
I  am trying to do migration 

            **\Artisan::call("tenants:artisan \"migrate --path=database/migrations/tenant_migrations --database=tenant\" --tenant={$idcheck->id}  " );**

**this command works on localhost perfectly** 

these are the 2 lines before the error message 
 DB::purge('landlord');
            DB::setDefaultConnection('landlord');

**on production error message is 
```log
[2021-05-26 08:50:57] production.ERROR: Undefined constant "STDIN" {"exception":"[object] (Error(code: 0): Undefined constant \"STDIN\" at /home/forge/woomultistock.com/vendor/symfony/console/Helper/QuestionHelper.php:110)
[stacktrace]**
#0 /home/forge/woomultistock.com/vendor/symfony/console/Helper/QuestionHelper.php(64): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk()
#1 /home/forge/woomultistock.com/vendor/symfony/console/Style/SymfonyStyle.php(365): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask()
#2 /home/forge/woomultistock.com/vendor/symfony/console/Style/SymfonyStyle.php(293): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion()
#3 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php(133): Symfony\\Component\\Console\\Style\\SymfonyStyle->confirm()
#4 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(29): Illuminate\\Console\\Command->confirm()
#5 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(72): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->confirmToProceed()
#6 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#7 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#11 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#12 /home/forge/woomultistock.com/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#13 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 /home/forge/woomultistock.com/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#15 /home/forge/woomultistock.com/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /home/forge/woomultistock.com/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#17 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#18 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(184): Illuminate\\Console\\Application->run()
#19 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(263): Illuminate\\Console\\Application->call()
#20 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
#21 /home/forge/woomultistock.com/vendor/spatie/laravel-multitenancy/src/Commands/TenantsArtisanCommand.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic()
#22 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->handle()
#23 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#27 /home/forge/woomultistock.com/vendor/spatie/laravel-multitenancy/src/Commands/Concerns/TenantAware.php(34): Illuminate\\Container\\Container->call()
#28 /home/forge/woomultistock.com/vendor/spatie/laravel-multitenancy/src/Models/Tenant.php(95): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->Spatie\\Multitenancy\\Commands\\Concerns\\{closure}()
#29 /home/forge/woomultistock.com/vendor/spatie/laravel-multitenancy/src/Commands/Concerns/TenantAware.php(34): Spatie\\Multitenancy\\Models\\Tenant->execute()
#30 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(655): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->Spatie\\Multitenancy\\Commands\\Concerns\\{closure}()
#31 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(740): Illuminate\\Support\\LazyCollection->Illuminate\\Support\\{closure}()
#32 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(453): Illuminate\\Support\\LazyCollection->reduce()
#33 /home/forge/woomultistock.com/vendor/spatie/laravel-multitenancy/src/Commands/Concerns/TenantAware.php(35): Illuminate\\Support\\LazyCollection->sum()
#34 /home/forge/woomultistock.com/vendor/symfony/console/Command/Command.php(256): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->execute()
#35 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#36 /home/forge/woomultistock.com/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#37 /home/forge/woomultistock.com/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#38 /home/forge/woomultistock.com/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#39 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#40 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(184): Illuminate\\Console\\Application->run()
#41 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(263): Illuminate\\Console\\Application->call()
#42 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
#43 /home/forge/woomultistock.com/app/Actions/Fortify/CreateNewUser.php(173): Illuminate\\Support\\Facades\\Facade::__callStatic()
#44 /home/forge/woomultistock.com/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php(54): App\\Actions\\Fortify\\CreateNewUser->create()
#45 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Fortify\\Http\\Controllers\\RegisteredUserController->store()
#46 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#47 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#48 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#49 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#50 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#51 /home/forge/woomultistock.com/app/Http/Middleware/RedirectIfAuthenticated.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectIfAuthenticated->handle()
#53 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#55 /home/forge/woomultistock.com/app/Http/Middleware/GenerateMenus.php(242): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\GenerateMenus->handle()
#57 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#59 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#61 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#63 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#65 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#66 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#68 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#70 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#72 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#73 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#74 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#75 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#76 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#77 /home/forge/woomultistock.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#79 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#81 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#82 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#84 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#85 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#87 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#89 /home/forge/woomultistock.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#91 /home/forge/woomultistock.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#93 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#95 /home/forge/woomultistock.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#96 /home/forge/woomultistock.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#97 {main}
"} 
```

**Comment by masterix21** [comment]
Are you using PHP 8?

**Comment by rogerad** [comment]
Hi
I am using php 8.0.5

**Comment by masterix21** [comment]
Try like so:
```php
Artisan::call("tenants:artisan \"migrate --force --path=database/migrations/tenant_migrations --database=tenant\" --tenant={$idcheck->id}");
```

**Comment by rogerad** [comment]
thank you the change works perfectly - all fixed
