### ISSUE TITLE
Installation issue - Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by nextloopdev** [spatie/laravel-multitenancy#287]
Installing on Laravel 7 running PHP 7.4

````
php artisan --version
# Laravel Framework 7.30.4

php -v
# PHP 7.4.13 (cli)

````

````
composer update

composer require "spatie/laravel-multitenancy:^1.0"

````

Throws up this error at the end

````
In QueueManager.php line 156:

  Trying to access array offset on value of type null
````

Error Log

````
[2021-09-01 11:54:41] production.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\QueueManager.php:156)
[stacktrace]
#0 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\QueueManager.php(156): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', 'D:\\application...', 156, Array)
#1 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\QueueManager.php(138): Illuminate\\Queue\\QueueManager->resolve('file')
#2 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\QueueManager.php(258): Illuminate\\Queue\\QueueManager->connection()
#3 D:\\application\\vendor\\spatie\\laravel-multitenancy\\src\\Actions\\MakeQueueTenantAwareAction.php(34): Illuminate\\Queue\\QueueManager->__call('createPayloadUs...', Array)
#4 D:\\application\\vendor\\spatie\\laravel-multitenancy\\src\\Actions\\MakeQueueTenantAwareAction.php(18): Spatie\\Multitenancy\\Actions\\MakeQueueTenantAwareAction->listenForJobsBeingQueued()
#5 D:\\application\\vendor\\spatie\\laravel-multitenancy\\src\\MultitenancyServiceProvider.php(72): Spatie\\Multitenancy\\Actions\\MakeQueueTenantAwareAction->execute()
#6 D:\\application\\vendor\\spatie\\laravel-multitenancy\\src\\MultitenancyServiceProvider.php(33): Spatie\\Multitenancy\\MultitenancyServiceProvider->configureQueue()
#7 [internal function]: Spatie\\Multitenancy\\MultitenancyServiceProvider->boot()
#8 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): call_user_func_array(Array, Array)
#9 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(867): Illuminate\\Container\\Container->call(Array)
#14 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\Multitenancy\\MultitenancyServiceProvider))
#15 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\Multitenancy\\MultitenancyServiceProvider), 23)
#16 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(851): array_walk(Array, Object(Closure))
#17 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#18 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#19 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#20 D:\\application\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#21 D:\\application\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
````

**Comment by nextloopdev** [comment]
I found the solution here

https://github.com/spatie/laravel-multitenancy/issues/175
