### ISSUE TITLE
Job failing with: Error: Call to a member function prepare()

### ISSUE THREAD

**Issue by pgartin** [spatie/laravel-multitenancy#358]
### Discussed in https://github.com/spatie/laravel-multitenancy/discussions/356

<div type='discussions-op-text'>

<sup>Originally posted by **pgartin** April  8, 2022</sup>
I have a particular job failing with the following error around 50% of the time:

`Error: Call to a member function prepare() on null in /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368`

This Job is being dispatched in a batch within another job. This is where the job is dispatched. (The job is in the $fieldJobs array):
````
Bus::chain([
                $farmJob,
                function () use ($fieldJobs) {
                    Bus::batch($fieldJobs)->dispatch();
                },
            ])->dispatch();
````
Here is the job that is failing:
````
<?php

namespace App\Jobs;

...

class SendFieldToEcoProducer implements ShouldQueue
{
    use Batchable, Dispatchable, InteractsWithQueue, Queueable;
    use EcoLogin;

    protected Field $field;
    protected User $user;

    public $timeout = 60 * 3;
    public $tries = 1;

    /**
     * Create a new job instance.
     *
     * @param \App\Models\Field $field
     * @param \App\Models\User $user
     */
    public function __construct(Field $field, User $user)
    {
        $this->field = $field;
        $this->user = $user;
    }

    /**
     * Execute the job.
     *
     * @return void
     * @throws \Exception
     */
    public function handle()
    {
        if (!Tenant::checkCurrent()) {
            throw new \Exception("No Tenant Recognized");
        }

           ...

     }
}
````
Here is my mulitenancy.php file:

````
return [
    'tenant_finder' => \Spatie\Multitenancy\TenantFinder\DomainTenantFinder::class,
    'tenant_artisan_search_fields' => [
        'id',
    ],
    'switch_tenant_tasks' => [
        \App\Multitenancy\Tasks\SwitchTenantDatabaseTask::class,
        \Spatie\Multitenancy\Tasks\PrefixCacheTask::class,
    ],
    'tenant_model' => \Spatie\Multitenancy\Models\Tenant::class,
    'queues_are_tenant_aware_by_default' => true,
    'tenant_database_connection_name' => 'tenant',
    'landlord_database_connection_name' => 'landlord',
    'current_tenant_container_key' => 'currentTenant',
    'actions' => [
        'make_tenant_current_action' => MakeTenantCurrentAction::class,
        'forget_current_tenant_action' => ForgetCurrentTenantAction::class,
        'make_queue_tenant_aware_action' => MakeQueueTenantAwareAction::class,
        'migrate_tenant' => MigrateTenantAction::class,
    ],
    'queueable_to_job' => [
        SendQueuedMailable::class => 'mailable',
        SendQueuedNotifications::class => 'notification',
        CallQueuedListener::class => 'class',
        BroadcastEvent::class => 'event',
    ],
````

And here is some relevant env variables which I have confirmed are what are used in the config:
````
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
````

Stack trace:
````


Stack trace:
--
#0   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705):  Illuminate\Database\Connection->Illuminate\Database\{closure}()
#1   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672):  Illuminate\Database\Connection->runQueryCallback()
#2   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376):  Illuminate\Database\Connection->run()
#3   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414):  Illuminate\Database\Connection->select()
#4   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402):  Illuminate\Database\Query\Builder->runSelect()
#5   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936):   Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#6   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2403):  Illuminate\Database\Query\Builder->onceWithColumns()
#7   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(294):  Illuminate\Database\Query\Builder->get()
#8   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(82):  Illuminate\Database\Query\Builder->first()
#9   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Bus/Batchable.php(24):  Illuminate\Bus\DatabaseBatchRepository->find()
#10   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(184):  App\Jobs\SendFieldToEcoProducer->batch()
#11   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(78):   Illuminate\Queue\CallQueuedHandler->ensureSuccessfulBatchJobIsRecorded()
#12   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98):  Illuminate\Queue\CallQueuedHandler->call()
#13   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428):  Illuminate\Queue\Jobs\Job->fire()
#14   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378):  Illuminate\Queue\Worker->process()
#15   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172):  Illuminate\Queue\Worker->runJob()
#16   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117):  Illuminate\Queue\Worker->daemon()
#17   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101):  Illuminate\Queue\Console\WorkCommand->runWorker()
#18   /home/forge/landlord.swof.com/vendor/laravel/horizon/src/Console/WorkCommand.php(51):  Illuminate\Queue\Console\WorkCommand->handle()
#19   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36):  Laravel\Horizon\Console\WorkCommand->handle()
#20   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40):  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93):  Illuminate\Container\Util::unwrapIfClosure()
#22   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37):  Illuminate\Container\BoundMethod::callBoundMethod()
#23   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653):  Illuminate\Container\BoundMethod::call()
#24   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136):  Illuminate\Container\Container->call()
#25 /home/forge/landlord.swof.com/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#26   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121):  Symfony\Component\Console\Command\Command->run()
#27 /home/forge/landlord.swof.com/vendor/symfony/console/Application.php(1015): Illuminate\Console\Command->run()
#28   /home/forge/landlord.swof.com/vendor/symfony/console/Application.php(299):  Symfony\Component\Console\Application->doRunCommand()
#29 /home/forge/landlord.swof.com/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#30   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(94):  Symfony\Component\Console\Application->run()
#31   /home/forge/landlord.swof.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129):  Illuminate\Console\Application->run()
#32 /home/forge/landlord.swof.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#33 {main}
````

Thanks in advance for taking a look at this. Let me know if you need other specific information.

Best,

Peter</div>

**Comment by masterix21** [comment]
Take a look here:
https://spatie.be/docs/laravel-multitenancy/v2/basic-usage/making-queues-tenant-aware#content-make-specific-jobs-tenant-aware

**Comment by pgartin** [comment]
Yes I've read the docs, thank you. If you are implying that my job should be implementing the `TenantAware` class, then I have tried adding that. Though the docs make it sound like that shouldn't be necessary with `'queues_are_tenant_aware_by_default' => true`.

If there is something else missing let me know.

**Comment by dirkam** [comment]
I have the same problem with using Bus::batch.
@pgartin did you find a solution?

**Comment by masterix21** [comment]
Please create a GitHub repository to reproduce the issue so we can fix it. Thanks.

**Comment by truthytech** [comment]
@pgartin did you ever resolve this? I have the same issue but with queue and session set as database and the job is tenant aware.
