### ISSUE TITLE
base table or view not found with AWS SQS queue for job TenantAware

### ISSUE THREAD

**Issue by MattWiseParking** [spatie/laravel-multitenancy#505]
Hi

I am receiving intermittent issues with a job that sometimes it works sometimes it doesnt.   I receive the following error:

```
Base table or view not found: 1146 Table 'db_lgnhs.tenants' doesn't exist (Connection: landlord, SQL: select * from `tenants` where `tenants`.`id` = 3 limit 1)
```

The field in my multitenancy is set:

`'queues_are_tenant_aware_by_default' => false,`

The Job class:

```php
class ProcessAnprFactoryJob implements ShouldQueue,TenantAware
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $carparkAnprRead;

    public $carparkCamera;

    public $vehicle;
    /**
     * Create a new job instance.
     */
    public function __construct($carparkAnprRead,$carparkCamera,$vehicle)
    {
        $this->carparkAnprRead = $carparkAnprRead;
        $this->carparkCamera = $carparkCamera;
        $this->vehicle = $vehicle;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {

        //do some coding
        activity('ANPR API')->log('the anpr factory job has started');
        $factory = new AnprFactory();
        $factory->process($this->carparkAnprRead, $this->carparkCamera,$this->vehicle);
        activity('ANPR APIP')->log('the anpr factory job has ended');
    }

    /**
     * Handle a job failure.
     */
    public function failed(Throwable $exception): void
    {
        activity('ANPR API')->log('Failed: '.$exception->getMessage());
    }
}
```

Sometimes the job fails with the above error and some times it doesnt, its a but hit and miss, more recently the job has failed
There is no other jobs execute inside the `$factory->process` code

I am using:

Laravel version 10.13.5
spatie multi tenancy version: 3.0.3

the client calling the above job is in fact in the api routes, several tests that the tenant id is being called correctly from this code.

Struggling to understand why its causing intermittent issues?  should i pass the tenant ID to the job, and make the job NotTenantAware then in the code just call `$tenant = app('currentTenant'); $tenant->id`

**Comment by masterix21** [comment]
Hi @MattWiseParking 

What is your default connection?

**Comment by MattWiseParking** [comment]
dump of the error below:

Connection Name: Exception: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_lgnhs.tenants' doesn't exist in /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php:416 Stack trace: #0 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): PDO->prepare('select * from ...&#039;) #1 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\Database\Connection-&gt;Illuminate\Database\{closure}(&#039;select * from ...', Array) #2 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(934): Illuminate\Database\Connection->runQueryCallback('select * from ...&#039;, Array, Object(Closure)) #3 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(914): Illuminate\Database\Connection-&gt;tryAgainIfCausedByLostConnection(Object(Illuminate\Database\QueryException), &#039;select * from ...', Array, Object(Closure)) #4 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(758): Illuminate\Database\Connection->handleQueryException(Object(Illuminate\Database\QueryException), 'select * from ...&#039;, Array, Object(Closure)) #5 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection-&gt;run(&#039;select * from ...', Array, Object(Closure)) #6 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2736): Illuminate\Database\Connection->select('select * from `...', Array, true) #7 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2724): Illuminate\Database\Query\Builder->runSelect() #8 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3278): Illuminate\Database\Query\Builder->Illuminate\Database\Query{closure}() #9 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2725): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure)) #10 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(717): Illuminate\Database\Query\Builder->get(Array) #11 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(701): Illuminate\Database\Eloquent\Builder->getModels(Array) #12 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\Database\Eloquent\Builder->get(Array) #13 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(443): Illuminate\Database\Eloquent\Builder->first(Array) #14 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->find(3) #15 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2335): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'find', Array) #16 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2347): Illuminate\Database\Eloquent\Model->__call('find', Array) #17 /var/app/current/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(105): Illuminate\Database\Eloquent\Model::__callStatic('find', Array) #18 /var/app/current/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(132): Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction->findTenant(Object(Illuminate\Queue\Events\JobProcessing)) #19 /var/app/current/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(46): Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction->bindOrForgetCurrentTenant(Object(Illuminate\Queue\Events\JobProcessing)) #20 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction->Spatie\Multitenancy\Actions{closure}(Object(Illuminate\Queue\Events\JobProcessing)) #21 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events{closure}('Illuminate\Queu...', Array) #22 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(653): Illuminate\Events\Dispatcher->dispatch('Illuminate\Queu...') #23 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(426): Illuminate\Queue\Worker->raiseBeforeJobEvent('sqs', Object(Illuminate\Queue\Jobs\SqsJob)) #24 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process('sqs', Object(Illuminate\Queue\Jobs\SqsJob), Object(Illuminate\Queue\WorkerOptions)) #25 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\SqsJob), 'sqs', Object(Illuminate\Queue\WorkerOptions)) #26 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(138): Illuminate\Queue\Worker->daemon('sqs', 'mycarpass.fifo', Object(Illuminate\Queue\WorkerOptions)) #27 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(121): Illuminate\Queue\Console\WorkCommand->runWorker('sqs', 'mycarpass.fifo') #28 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle() #29 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #30 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #31 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #32 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #33 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call(Array) #34 /var/app/current/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #35 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #36 /var/app/current/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #37 /var/app/current/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #38 /var/app/current/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #39 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #40 /var/app/current/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_lgnhs.tenants' doesn't exist (Connection: landlord, SQL: select * from tenants where tenants.id = 3 limit 1) in /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795 Stack trace: #0 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(934): Illuminate\Database\Connection->runQueryCallback('select * from ...&#039;, Array, Object(Closure)) #1 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(914): Illuminate\Database\Connection-&gt;tryAgainIfCausedByLostConnection(Object(Illuminate\Database\QueryException), &#039;select * from ...', Array, Object(Closure)) #2 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(758): Illuminate\Database\Connection->handleQueryException(Object(Illuminate\Database\QueryException), 'select * from ...&#039;, Array, Object(Closure)) #3 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection-&gt;run(&#039;select * from ...', Array, Object(Closure)) #4 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2736): Illuminate\Database\Connection->select('select * from `...', Array, true) #5 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2724): Illuminate\Database\Query\Builder->runSelect() #6 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3278): Illuminate\Database\Query\Builder->Illuminate\Database\Query{closure}() #7 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2725): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure)) #8 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(717): Illuminate\Database\Query\Builder->get(Array) #9 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(701): Illuminate\Database\Eloquent\Builder->getModels(Array) #10 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\Database\Eloquent\Builder->get(Array) #11 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(443): Illuminate\Database\Eloquent\Builder->first(Array) #12 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->find(3) #13 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2335): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'find', Array) #14 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2347): Illuminate\Database\Eloquent\Model->__call('find', Array) #15 /var/app/current/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(105): Illuminate\Database\Eloquent\Model::__callStatic('find', Array) #16 /var/app/current/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(132): Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction->findTenant(Object(Illuminate\Queue\Events\JobProcessing)) #17 /var/app/current/vendor/spatie/laravel-multitenancy/src/Actions/MakeQueueTenantAwareAction.php(46): Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction->bindOrForgetCurrentTenant(Object(Illuminate\Queue\Events\JobProcessing)) #18 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction->Spatie\Multitenancy\Actions{closure}(Object(Illuminate\Queue\Events\JobProcessing)) #19 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events{closure}('Illuminate\Queu...', Array) #20 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(653): Illuminate\Events\Dispatcher->dispatch('Illuminate\Queu...') #21 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(426): Illuminate\Queue\Worker->raiseBeforeJobEvent('sqs', Object(Illuminate\Queue\Jobs\SqsJob)) #22 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process('sqs', Object(Illuminate\Queue\Jobs\SqsJob), Object(Illuminate\Queue\WorkerOptions)) #23 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\SqsJob), 'sqs', Object(Illuminate\Queue\WorkerOptions)) #24 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(138): Illuminate\Queue\Worker->daemon('sqs', 'mycarpass.fifo', Object(Illuminate\Queue\WorkerOptions)) #25 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(121): Illuminate\Queue\Console\WorkCommand->runWorker('sqs', 'mycarpass.fifo') #26 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle() #27 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #28 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #29 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #30 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #31 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call(Array) #32 /var/app/current/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #33 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #34 /var/app/current/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #35 /var/app/current/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #36 /var/app/current/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #37 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #38 /var/app/current/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #39 {main}

**Comment by masterix21** [comment]
The issue concerns your landlord connection: could you make it default in your .env? 

Are you sure that `db_lgnhs` database contains the table tenants?

**Comment by MattWiseParking** [comment]
@masterix21 table tenants should only be in the landlord connection database which is set in the .env file initially.

If I make the landlord connection default I receive an error: your tenant_database_connection_name is empty, please make the tenant connection.

If i change the tenant_database_connection_name to tenant then every entry in the tenants table becomes the landlords database.

I think its something to do with the landlord connection which doesn't seem to be setting the database, hence it defaults to the tenant database instead and tries to find the tenants table in the db_lgnhs database.

I dont know if this is the issue, but none of my models are set to use UseTenantsConnection except the Tenant model which I created and extended from the original Tenants model which defaults to useLandlordConnection.

Other than that I am out of ideas.

**Comment by anotherZero** [comment]
I believe this is the same issue I've been struggling with as well.  I have found that my scheduled queued jobs seem to work OK if I keep queuing items at a regular interval.  However, if I don't have a job drop onto the queue for ~15 minutes it tends to fail.

Here is the relevant portion of the stack trace found on the failed jobs list in horizon.  It indicates that it's trying to search for the tenant but it is using the tenant database when it should be using the landlord connection.  The landlord user doesn't have permissions to read the tenant databases, and it's trying to read the `landlord_site_info` table in the `tenant` database.
```
Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1044] Access denied for user 'landlorduser'@'localhost' to database 'tenant' (Connection: landlord, SQL: select * from `landlord_site_info` where `landlord_site_info`.`id` = 6 limit 1) in /var/www/mysite/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822
```

I'd be happy to provide any additional info that can help get to the bottom of this.

**Comment by MattWiseParking** [comment]
@anotherZero same here, it happens once a day after nothing sent to the queue for approx 8 hours.

**Comment by MattWiseParking** [comment]
@masterix21 do you have an update regarding this issue?

**Comment by masterix21** [comment]
Hi @MattWiseParking, sorry, but no, because I have no AWS SQS instances.

**Comment by gssj85** [comment]
I'm having something similar when job starts the default connection is set to tenant the tenant connection with null host

**Comment by masterix21** [comment]
@gssj85, please post your error.

**Comment by MattWiseParking** [comment]
this is still an issue and requires support

**Comment by MattWiseParking** [comment]
Re open the issue please

From: spatie-bot ***@***.***>
Date: Monday, 9 September 2024 at 11:09
To: spatie/laravel-multitenancy ***@***.***>
Cc: Matthew Haselip ***@***.***>, Mention ***@***.***>
Subject: Re: [spatie/laravel-multitenancy] base table or view not found with AWS SQS queue for job TenantAware (Issue #505)

Dear contributor,

because this issue seems to be inactive for quite some time now, I've automatically closed it. If you feel this issue deserves some attention from my human colleagues feel free to reopen it.

**Comment by Bouhaddi** [comment]
yes same issue here

**Comment by MattWiseParking** [comment]
this is now resolved.  basically i was using an old version of supervisor running on aws linux 2.  upgraded environment to amazon linux 2023 running php 8.3 and had to change supervisor script files, i can paste the files if anybody needs them?
